### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/mapa-mental-web-3-DuilioAquino10#1]
[Mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-DuilioAquino10/files/8406462/Mapa.mental.pdf)

**Comment by IsaHuerta23** [comment]
Manejo conceptual y dominio del tema: 25 puntos.
Relación entre los conceptos incluidos en el mapa: 25 puntos.
Calidad de la presentación: 25 puntos.
Jerarquía: 25 puntos.
TOTAL DE PUNTOS: 100 puntos.
CALIFICACIÓN: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
